# Default initial positions for fact_robot's ros2_control fake system

initial_positions:
  joint_1_s: 0
  joint_2_l: 0
  joint_3_u: 0
  joint_4_r: 0
  joint_5_b: 0
  joint_6_t: 0
  main_left_finger_joint: 0
  main_right_finger_joint: 0